### ISSUE TITLE
Share to 2 channels

### ISSUE THREAD

**Issue by rsabin** [GAM3RG33K/SendToDiscrodExtention#3]
It is possible to share to 2 channels simultaneously when they have the same name instead only of the last added channel? I have two different servers to manage and this will be awesome.
Or another way to do this. Right now I have to share two times.

**Comment by GAM3RG33K** [comment]
This is actually a good idea.

I'll try to add this as soon as possible.
Thanks for reaching out. Keep giving feed backs.✌

**Comment by GAM3RG33K** [comment]
This feature is added and now released in Extension v2.1.0.2.
Please update the extension.

Description of the feature:
To  Broadcast to multiple channels with single click.
 Just add a ';'(of course without quotes) between two-channel URLs and save them under a single channel name.

For example:
 if you have
 • #ch1 : [URL_OF_CHANNEL_1]
 • #ch2 : [URL_OF_CHANNEL_2]

then save them as :
 •#broadcast:  [URL_OF_CHANNEL_1]; [URL_OF_CHANNEL_2]

Select #broadcast to broadcast content to both #ch1 and #ch2
